(function(){
 if(window.__gaplessQueueV44)return;window.__gaplessQueueV44=true;
 const cache=new Map(),inflight=new Map();let unlocked=false,prime=null,announcementBusy=false,currentAudio=null;
 function paths(category,key){const s=String(key||'').trim(),o=['audio/'+s+'.wav'];try{if(typeof audioPaths==='function'){const p=audioPaths(category,key);if(Array.isArray(p))o.push(...p)}}catch(e){}return [...new Set(o)].filter(x=>/\.wav(?:$|\?)/i.test(x))}
 async function url(path){if(cache.has(path))return cache.get(path);if(inflight.has(path))return inflight.get(path);const q=(async()=>{try{const r=await fetch(path,{cache:'force-cache'});if(!r.ok)return null;const b=await r.blob();if(!b.size)return null;const u=URL.createObjectURL(b);cache.set(path,u);return u}catch(e){return null}finally{inflight.delete(path)}})();inflight.set(path,q);return q}
 async function find(c,k){for(const p of paths(c,k)){const u=await url(p);if(u)return u}return null}
 function tts(c,k){if(c==='phrases_en')return{text:k==='thisstopis'?'This stop is':k,lang:'en-US'};if(c==='stops'&&/ \(1\)$/.test(k))return{text:String(k).replace(/ \(1\)$/,''),lang:'en-US'};if(c==='stops')return{text:String(k)+'입니다',lang:'ko-KR'};return{text:({'이번정류소':'이번 정류소는','다음정류소':'다음 정류소는','종점입니다':'종점입니다'})[k]||k,lang:'ko-KR'}}
 function play(u){return new Promise(resolve=>{const a=new Audio();currentAudio=a;a.preload='auto';a.playsInline=true;a.src=u;a.volume=typeof guideVolume==='number'?guideVolume:1;a.playbackRate=Math.max(.1,typeof guideRate==='number'?guideRate:1);let done=false;const fin=x=>{if(done)return;done=true;clearTimeout(to);if(currentAudio===a)currentAudio=null;resolve(x)};a.onended=()=>fin(true);a.onerror=()=>fin(false);const to=setTimeout(()=>{try{a.pause()}catch(e){}fin(false)},120000);try{const p=a.play();if(p&&p.catch)p.catch(()=>fin(false))}catch(e){fin(false)}})}
 async function speak(x){try{if(typeof speakText==='function')return await speakText(x.text,x.lang)}catch(e){}return false}
 async function one(c,k){const u=await find(c,k);if(u){if(await play(u))return true;await unlock(true);return await play(u)}return await speak(tts(c,k))}
 async function unlock(force=false){if(unlocked&&!force)return;try{if(!prime){prime=new Audio('audio/thisstopis.wav');prime.playsInline=true;prime.preload='auto';prime.volume=0}const p=prime.play();if(p&&p.then)await p;prime.pause();prime.currentTime=0;unlocked=true}catch(e){}}
 ['touchstart','pointerdown','click'].forEach(e=>document.addEventListener(e,()=>unlock(),{capture:true,passive:true}));window.unlockAudioForMobile=unlock;
 try{announceArrival=async function(stop,next){if(!guideTtsOn||announcementBusy)return;announcementBusy=true;try{try{speechSynthesis.cancel()}catch(e){}const k=stop.audioName||stop.name;const seq=[['phrases','이번정류소'],['stops',k],next?['phrases','다음정류소']:['phrases','종점입니다'],...(next?[['stops',next.audioName||next.name]]:[]),['phrases_en','thisstopis'],['stops',k+' (1)']];for(const x of seq)await one(x[0],x[1])}finally{announcementBusy=false}}}catch(e){}
})();